export const temperaturasIcones = {
  0: ['./images/clouds-2.svg', 'Nuvens'],
  1: ['./images/clouds-2.svg', 'Nuvens'],
  2: ['./images/clouds-2.svg', 'Nuvens'],
  3: ['./images/clouds-2.svg', 'Nuvens'],
  4: ['./images/clouds-2.svg', 'Nuvens'],
  5: ['./images/clouds-2.svg', 'Nuvens'],
  6: ['./images/clouds-2.svg', 'Nuvens'],
  7: ['./images/clouds-2.svg', 'Nuvens'],
  8: ['./images/01-sun-cloud.svg', 'Sol com nuvens'],
  9: ['./images/01-sun-cloud.svg', 'Sol com nuvens'],
  10: ['./images/01-sun-cloud.svg', 'Sol com nuvens'],
  11: ['./images/01-sun-cloud.svg', 'Sol com nuvens'],
  12: ['./images/01-sun-cloud.svg', 'Sol com nuvens'],
  13: ['./images/01-sun-cloud.svg', 'Sol com nuvens'],
  14: ['./images/01-sun-cloud.svg', 'Sol com nuvens'],
  15: ['./images/01-sun-cloud.svg', 'Sol com nuvens'],
  16: ['./images/01-sun-cloud.svg', 'Sol com nuvens'],
  17: ['./images/02-sun-cloud.svg', 'Sol com nuvens'],
  18: ['./images/02-sun-cloud.svg', 'Sol com nuvens'],
  19: ['./images/02-sun-cloud.svg', 'Sol com nuvens'],
  20: ['./images/02-sun-cloud.svg', 'Sol com nuvens'],
  21: ['./images/02-sun-cloud.svg', 'Sol com nuvens'],
  22: ['./images/02-sun-cloud.svg', 'Sol com nuvens'],
  23: ['./images/02-sun-cloud.svg', 'Sol com nuvens'],
  24: ['./images/02-sun-cloud.svg', 'Sol com nuvens'],
  25: ['./images/sun.svg', 'Sol'],
  26: ['./images/sun.svg', 'Sol'],
  27: ['./images/sun.svg', 'Sol'],
  28: ['./images/sun.svg', 'Sol'],
  29: ['./images/sun.svg', 'Sol'],
  30: ['./images/sun.svg', 'Sol'],
  31: ['./images/sun.svg', 'Sol'],
  32: ['./images/sun.svg', 'Sol'],
  33: ['./images/sun.svg', 'Sol'],
  34: ['./images/sun.svg', 'Sol'],
  35: ['./images/sun.svg', 'Sol'],
  36: ['./images/sun.svg', 'Sol'],
  37: ['./images/sun.svg', 'Sol'],
  38: ['./images/sun.svg', 'Sol'],
  39: ['./images/sun.svg', 'Sol'],
  40: ['./images/sun.svg', 'Sol'],
};
